### PR TITLE
Documentation for MemoizedDeepRecursiveFunction

### LINKED ISSUE #213: Misleading/Wrong example in the documentation about Memoization
First, thanks for the arrow library.

This issue originated from a conversation in the #arrow channel on the kotlinlang Slack. Here is the link to the thread: [Slack Thread](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1688655384688549)

I was quite surprised when reading the documentation and came across the [memoize function in arrow](https://arrow-kt.io/learn/collections-functions/recursive/#memoization). In the documentation, it's illustrated with the Fibonacci sequence, which requires recursive calls. According to the documentation, you can take a simple `DeepRecursiveFunction`, apply `.memoize`, and obtain a function in a `val` that takes care of memoizing all the calls. No need to modify the original function. The promise was so enticing that I decided to test it out myself.

However, I encountered two issues:

1. The code from the documentation doesn't compile as is.
2. After making some slight modifications to make it compile, it doesn't behave as expected at all.

Here are the details for each problem:

1. I copied and pasted the code from the documentation to test it:
```
import arrow.core.memoize

val fibonacciWorker = DeepRecursiveFunction<Int, Int> { n ->
    when (n) {
        0 -> 0
        1 -> 1
        else -> callRecursive(n - 1) + callRecursive(n - 2)
    }
}

val fibonacciMemoized = ::fibonacciWorker.memoize()

fun fibonacci(n: Int): Int {
    require(n >= 0)
    return fibonacciMemoized(n)
}
```
I am using:
- IntelliJ 2023.2 EAP
- Kotlin 1.8.10
- Gradle Wrapper 7.6
- Arrow 1.2.0-RC
- Compile flags : languageVersion = 1.9 and context receivers enabled.

This code doesn't compile, and the error message is as follows:
```
e: file:///Users/.../fibo.kt:18:12 Type mismatch: inferred type is DeepRecursiveFunction<Int, Int> but Int was expected
```
It seems that the `memoize` function doesn't work as expected on a `DeepRecursiveFunction`.

2. Therefore, I modified the code by wrapping the `DeepRecursiveFunction` inside a regular function:
```
import arrow.core.memoize

val fibonacciWorker = DeepRecursiveFunction<Int, Int> { n ->
    print(".") // I added this print statement in order to visualize all the recursive calls.
    when (n) {
        0 -> 0
        1 -> 1
        else -> callRecursive(n - 1) + callRecursive(n - 2)
    }
}

fun fib(n: Int) = fibonacciWorker(n) // wrap the DeepRecursiveFunction in a regular one

val fibonacciMemoized = ::fib.memoize()

fun fibonacci(n: Int): Int {
    require(n >= 0)
    return fibonacciMemoized(n)
}

// Show that the memoize function actually memoize the call to hat function but not all the recursive calls
fun main() {
    println(fibonacci(4)) // .........3
    println(fibonacci(4)) // 3 => has been memoized
    println(fibonacci(3)) // .....2 => recursive calls have not been memoized
}
```
In this code, it compiles, but it doesn't produce the desired behavior. As shown in the main function, the wrapper function is memoized correctly, but the recursive calls are not. This is completely absurd for an example like the Fibonacci sequence, where memoizing the recursive calls is crucial.

The memoize function remains useful, but it seems that we will still need to manually implement memoization for recursive functions like Fibonacci 😞

### PR DESCRIPTION
**Pull request by serras**
Fixes #213

### CODE REVIEW

File: guide/src/test/kotlin/examples/example-recursive-03.kt [hunk 1]
```diff
@@ -3,22 +3,20 @@ package arrow.website.examples.exampleRecursive03
 
 import io.kotest.matchers.shouldBe
 
-import arrow.core.memoize
-
-val fibonacciMemoized = ::fibonacciWorker.memoize()
+import arrow.core.MemoizedDeepRecursiveFunction
 
+val fibonacciWorker = MemoizedDeepRecursiveFunction<Int, Int> { n ->
```
Comment (AcartN) [inline guide/src/test/kotlin/examples/example-recursive-03.kt:8]: It's not a big deal but wouldn't it be more appropriate to name this function "fibonacciMemoized" instead of "fibonacciWorker"?

**Review by AcartN — COMMENTED** [review]
I appreciate the improvements you've made, and it seems like you've addressed the issue with the example. However, now there is a lack of demonstration or illustration of the actual `.memoized()` function, which is designed to work seamlessly with any non-recursive method.

**Comment by serras** [comment]
> I appreciate the improvements you've made, and it seems like you've addressed the issue with the example. However, now there is a lack of demonstration or illustration of the actual `.memoized()` function, which is designed to work seamlessly with any non-recursive method.

I was actually debating what to do here. On the one hand, `memoized` works on every function; but if that function is recursive the recursive calls are not handled correctly. And if you're writing the recursive function by hand, you're better off using `DeepRecursiveFunction` than creating a double-recursive function in which the worker calls the memoized function and vice versa.

**Comment by AcartN** [comment]
> > I appreciate the improvements you've made, and it seems like you've addressed the issue with the example. However, now there is a lack of demonstration or illustration of the actual `.memoized()` function, which is designed to work seamlessly with any non-recursive method.
> 
> I was actually debating what to do here. On the one hand, `memoized` works on every function; but if that function is recursive the recursive calls are not handled correctly. And if you're writing the recursive function by hand, you're better off using `DeepRecursiveFunction` than creating a double-recursive function in which the worker calls the memoized function and vice versa.

In my opinion, there are really two cases:

- Recursive functions that need to use MemoizedDeepRecursiveFunction.
- Non-recursive functions that can simply use `.memoize()`. Some functions may take time to compute without making recursive calls, and in such cases, memoize is a good idea. However, I must admit that I don't have a specific example that comes to mind right now.

I believe that in the documentation, both the simple `.memoized()` approach for a function and the usage of MemoizedDeepRecursiveFunction should be discussed, with a clear explanation of the differences between them. For someone who is new to the documentation, it is not obvious at all, so providing explanations and even illustrating with examples would be beneficial

File: guide/src/test/kotlin/examples/example-recursive-03.kt (hunk 1 above)
Comment (AcartN) [reply guide/src/test/kotlin/examples/example-recursive-03.kt:8]: That actually makes sense

**Comment by serras** [comment]
@AcartN your explanation makes a lot of sense. I've just pushed a new commit with adds a new separate _Memoization_ section. I've decided to still have "recursive + memoized" live in the _Recursion_ section, because I feel it makes sense to tell the story in that way. In _Memoization_ the discussion is about what are the limitations of `memoize` w.r.t. recursion, and then suggests `MemoizedDeepRecursiveFunction` as the preferred option if you control the function.

**Review by AcartN — APPROVED** [review]
Perfect! It appears to be very clear to me. The limitations and distinctions between the simple `.memoize()` and `MemoizedDeepRecursiveFunction` are explained effectively. Creating a new section for Memoize while maintaining the logical flow of the recursive function section is a good idea.

**Review by nomisRev — APPROVED** [review]

**Comment by nomisRev** [comment]
This documentation PR is blocked until we released `1.2.0`.
